//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFortisDeviceManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFortisDeviceManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительную информацию о программе можно узнать по ссылке:.
        /// </summary>
        public static string AboutProgramLabelForProgramLink {
            get {
                return ResourceManager.GetString("AboutProgramLabelForProgramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TFortis Device Manager - это программа для поиска устройств TFortis (управляемых коммутаторов серий PSW, SWU, трансляторов сухих контактов TELEPORT) производства ООО «Форт-Телеком» в сети, их конфигурирования и мониторинга..
        /// </summary>
        public static string AboutProgramm {
            get {
                return ResourceManager.GetString("AboutProgramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление в мониторинг.
        /// </summary>
        public static string AddingToMonitoring {
            get {
                return ResourceManager.GetString("AddingToMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г. Пермь, ул. Бульвар Гагарина, 65а.
        /// </summary>
        public static string AddressCompany {
            get {
                return ResourceManager.GetString("AddressCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтобы получать уведомления, добавьте его в список для рассылки в программе TFortisDeviceManager.
        /// </summary>
        public static string AddToMailingList {
            get {
                return ResourceManager.GetString("AddToMailingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить на топологию.
        /// </summary>
        public static string AddToMap {
            get {
                return ResourceManager.GetString("AddToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить в мониторинг.
        /// </summary>
        public static string AddToMonitoring {
            get {
                return ResourceManager.GetString("AddToMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки отправки оповещений.
        /// </summary>
        public static string AlertSendingSettings {
            get {
                return ResourceManager.GetString("AlertSendingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки оповещений.
        /// </summary>
        public static string AlertSettings {
            get {
                return ResourceManager.GetString("AlertSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема письма.
        /// </summary>
        public static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Экземпляр приложения уже запущен.
        /// </summary>
        public static string AlreadyRunningError {
            get {
                return ResourceManager.GetString("AlreadyRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык приложения.
        /// </summary>
        public static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки применены.
        /// </summary>
        public static string ApplySettingsSuccessful {
            get {
                return ResourceManager.GetString("ApplySettingsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка аутентификации.
        /// </summary>
        public static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TFortisDeviceManager | Аутентификация.
        /// </summary>
        public static string AuthenticationTitle {
            get {
                return ResourceManager.GetString("AuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        public static string AuthorisationError {
            get {
                return ResourceManager.GetString("AuthorisationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрывать уведомления автоматически.
        /// </summary>
        public static string AutoHideNotifications {
            get {
                return ResourceManager.GetString("AutoHideNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список пользователей, имеющих доступ к боту.
        /// </summary>
        public static string BotAccessList {
            get {
                return ResourceManager.GetString("BotAccessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список камер.
        /// </summary>
        public static string CameraList {
            get {
                return ResourceManager.GetString("CameraList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TFortisDeviceManager | Список камер.
        /// </summary>
        public static string CameraListTitle {
            get {
                return ResourceManager.GetString("CameraListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список камер.
        /// </summary>
        public static string CamerasList {
            get {
                return ResourceManager.GetString("CamerasList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверять.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите действие.
        /// </summary>
        public static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите столбцы....
        /// </summary>
        public static string ChooseColumns {
            get {
                return ResourceManager.GetString("ChooseColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл прошивки.
        /// </summary>
        public static string ChooseDfuFile {
            get {
                return ResourceManager.GetString("ChooseDfuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить фон.
        /// </summary>
        public static string ClearBackgroung {
            get {
                return ResourceManager.GetString("ClearBackgroung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить топологию.
        /// </summary>
        public static string ClearMap {
            get {
                return ResourceManager.GetString("ClearMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть меню.
        /// </summary>
        public static string CollapseMenu {
            get {
                return ResourceManager.GetString("CollapseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки отображения дополнительных столбцов таблиц.
        /// </summary>
        public static string ColumnVisibilitySettings {
            get {
                return ResourceManager.GetString("ColumnVisibilitySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие настройки.
        /// </summary>
        public static string CommonSettings {
            get {
                return ResourceManager.GetString("CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка конфигурации.
        /// </summary>
        public static string ConfigError {
            get {
                return ResourceManager.GetString("ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация.
        /// </summary>
        public static string Configuring {
            get {
                return ResourceManager.GetString("Configuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить для всех.
        /// </summary>
        public static string ConfirmToAll {
            get {
                return ResourceManager.GetString("ConfirmToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время непрерывной работы.
        /// </summary>
        public static string ContinuousOperationTime {
            get {
                return ResourceManager.GetString("ContinuousOperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания устройства. {0}.
        /// </summary>
        public static string CreateDeviceError {
            get {
                return ResourceManager.GetString("CreateDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темная.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удается подключиться к базе данных.
        /// </summary>
        public static string DatabaseConnectError {
            get {
                return ResourceManager.GetString("DatabaseConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на д..
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дней.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить из мониторинга.
        /// </summary>
        public static string DeleteFromMonitoring {
            get {
                return ResourceManager.GetString("DeleteFromMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство доступно.
        /// </summary>
        public static string DescriptionDeviceAvilable {
            get {
                return ResourceManager.GetString("DescriptionDeviceAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство недоступно.
        /// </summary>
        public static string DescriptionDeviceNotAvilable {
            get {
                return ResourceManager.GetString("DescriptionDeviceNotAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хост перезапущен.
        /// </summary>
        public static string DescriptionHostReloaded {
            get {
                return ResourceManager.GetString("DescriptionHostReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление устройства.
        /// </summary>
        public static string DeviceAdding {
            get {
                return ResourceManager.GetString("DeviceAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание устройства.
        /// </summary>
        public static string DeviceDescription {
            get {
                return ResourceManager.GetString("DeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство с таким IP уже есть на топологии.
        /// </summary>
        public static string DeviceExistsOnMapMessage {
            get {
                return ResourceManager.GetString("DeviceExistsOnMapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация об устройстве.
        /// </summary>
        public static string DeviceInformation {
            get {
                return ResourceManager.GetString("DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство уже в списке для мониторинга.
        /// </summary>
        public static string DeviceIsAlreadyAdded {
            get {
                return ResourceManager.GetString("DeviceIsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство с таким IP уже есть на карте.
        /// </summary>
        public static string DeviceIsAlreadyExists {
            get {
                return ResourceManager.GetString("DeviceIsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список устройств.
        /// </summary>
        public static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список устройств пуст.
        /// </summary>
        public static string DeviceListIsEmpty {
            get {
                return ResourceManager.GetString("DeviceListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство недоступно.
        /// </summary>
        public static string DeviceNotAvailable {
            get {
                return ResourceManager.GetString("DeviceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель c Id {0} не найдена в Json-файле.
        /// </summary>
        public static string DeviceNotFoundInJson {
            get {
                return ResourceManager.GetString("DeviceNotFoundInJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство не отвечает .
        /// </summary>
        public static string DeviceNotRespond {
            get {
                return ResourceManager.GetString("DeviceNotRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка устройства.
        /// </summary>
        public static string DeviceSettings {
            get {
                return ResourceManager.GetString("DeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки устройства.
        /// </summary>
        public static string DeviceSettingsTitle {
            get {
                return ResourceManager.GetString("DeviceSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройства в мониторинге.
        /// </summary>
        public static string DevicesInMonitoring {
            get {
                return ResourceManager.GetString("DevicesInMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список устройств в мониторинге.
        /// </summary>
        public static string DevicesInMonitoringList {
            get {
                return ResourceManager.GetString("DevicesInMonitoringList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройства не найдены.
        /// </summary>
        public static string DevicesNotFound {
            get {
                return ResourceManager.GetString("DevicesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица устройств.
        /// </summary>
        public static string DevicesTable {
            get {
                return ResourceManager.GetString("DevicesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройства с ввденным адресом нет в списке для мониторинга.
        /// </summary>
        public static string DeviceWithAddressNotFound {
            get {
                return ResourceManager.GetString("DeviceWithAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПО обновлено, повторите поиск.
        /// </summary>
        public static string DfuUpdated {
            get {
                return ResourceManager.GetString("DfuUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить LLDP.
        /// </summary>
        public static string EnableLLDP {
            get {
                return ResourceManager.GetString("EnableLLDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить PoE.
        /// </summary>
        public static string EnablePoe {
            get {
                return ResourceManager.GetString("EnablePoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить порт.
        /// </summary>
        public static string EnablePort {
            get {
                return ResourceManager.GetString("EnablePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить SNMP.
        /// </summary>
        public static string EnableSnmp {
            get {
                return ResourceManager.GetString("EnableSnmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить SNTP.
        /// </summary>
        public static string EnableSNTP {
            get {
                return ResourceManager.GetString("EnableSNTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите IP.
        /// </summary>
        public static string EnterIP {
            get {
                return ResourceManager.GetString("EnterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин и пароль.
        /// </summary>
        public static string EnterLoginAndPassword {
            get {
                return ResourceManager.GetString("EnterLoginAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при попытке очистить память.
        /// </summary>
        public static string ErrorWhileClearingFlash {
            get {
                return ResourceManager.GetString("ErrorWhileClearingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при попытке обновитьПО.
        /// </summary>
        public static string ErrorWhileUpdating {
            get {
                return ResourceManager.GetString("ErrorWhileUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при попытке загрузить файл.
        /// </summary>
        public static string ErrorWhileUploading {
            get {
                return ResourceManager.GetString("ErrorWhileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание события.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт событий.
        /// </summary>
        public static string EventExport {
            get {
                return ResourceManager.GetString("EventExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список событий с адресом.
        /// </summary>
        public static string EventListWithAddress {
            get {
                return ResourceManager.GetString("EventListWithAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица событий.
        /// </summary>
        public static string EventsTable {
            get {
                return ResourceManager.GetString("EventsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть меню.
        /// </summary>
        public static string ExpandMenu {
            get {
                return ResourceManager.GetString("ExpandMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разворачивать окно при аварии.
        /// </summary>
        public static string ExpandWindow {
            get {
                return ResourceManager.GetString("ExpandWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл слишком большой.
        /// </summary>
        public static string FileTooBig {
            get {
                return ResourceManager.GetString("FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка файла.
        /// </summary>
        public static string FileUploading {
            get {
                return ResourceManager.GetString("FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия прошивки.
        /// </summary>
        public static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список найденных устройств.
        /// </summary>
        public static string FoundedDevicesList {
            get {
                return ResourceManager.GetString("FoundedDevicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полный экран.
        /// </summary>
        public static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сетевой шлюз.
        /// </summary>
        public static string Gateway {
            get {
                return ResourceManager.GetString("Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат шлюза.
        /// </summary>
        public static string GatewayValidationError {
            get {
                return ResourceManager.GetString("GatewayValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для получения списка доступных комманд отправьте.
        /// </summary>
        public static string GetCommandList {
            get {
                return ResourceManager.GetString("GetCommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на получить список устройств в мониторинге.
        /// </summary>
        public static string GetDeviceListInMonitoring {
            get {
                return ResourceManager.GetString("GetDeviceListInMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповая настройка.
        /// </summary>
        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрывать уведомления через.
        /// </summary>
        public static string HideNotificationsAfter {
            get {
                return ResourceManager.GetString("HideNotificationsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние устройства.
        /// </summary>
        public static string HostStatus {
            get {
                return ResourceManager.GetString("HostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключен.
        /// </summary>
        public static string HostStatusDisabled {
            get {
                return ResourceManager.GetString("HostStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включен.
        /// </summary>
        public static string HostStatusEnabled {
            get {
                return ResourceManager.GetString("HostStatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезапущен.
        /// </summary>
        public static string HostStatusReloaded {
            get {
                return ResourceManager.GetString("HostStatusReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ч..
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить настройки.
        /// </summary>
        public static string ImportSettings {
            get {
                return ResourceManager.GetString("ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвертировать.
        /// </summary>
        public static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат IP-адреса.
        /// </summary>
        public static string IpValidationError {
            get {
                return ResourceManager.GetString("IpValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хранить события в базе данных.
        /// </summary>
        public static string KeepEventInDatabase {
            get {
                return ResourceManager.GetString("KeepEventInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://tfortis.ru/producty/po-tfortis-device-manager-new/.
        /// </summary>
        public static string LinkForProgramm {
            get {
                return ResourceManager.GetString("LinkForProgramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Местоположение.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAC адрес.
        /// </summary>
        public static string Mac {
            get {
                return ResourceManager.GetString("Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ponomarev@fort-telecom.ru.
        /// </summary>
        public static string MailForContact {
            get {
                return ResourceManager.GetString("MailForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта.
        /// </summary>
        public static string MainMenuGMap {
            get {
                return ResourceManager.GetString("MainMenuGMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика.
        /// </summary>
        public static string MainMenuGraphics {
            get {
                return ResourceManager.GetString("MainMenuGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Топология сети.
        /// </summary>
        public static string MainMenuMap {
            get {
                return ResourceManager.GetString("MainMenuMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мониторинг.
        /// </summary>
        public static string MainMenuMonitoring {
            get {
                return ResourceManager.GetString("MainMenuMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string MainMenuSearch {
            get {
                return ResourceManager.GetString("MainMenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string MainMenuSettings {
            get {
                return ResourceManager.GetString("MainMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ручное добавление.
        /// </summary>
        public static string ManualAdding {
            get {
                return ResourceManager.GetString("ManualAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провайдер карт.
        /// </summary>
        public static string MapProvider {
            get {
                return ResourceManager.GetString("MapProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки карты.
        /// </summary>
        public static string MapSettings {
            get {
                return ResourceManager.GetString("MapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маркеры.
        /// </summary>
        public static string Markers {
            get {
                return ResourceManager.GetString("Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м..
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мониторинг.
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки монитоиринга.
        /// </summary>
        public static string MonitoringConfiguration {
            get {
                return ResourceManager.GetString("MonitoringConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список устройств для мониторинга пуст.
        /// </summary>
        public static string MonitoringDevicesIsEmpty {
            get {
                return ResourceManager.GetString("MonitoringDevicesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки мониторинга.
        /// </summary>
        public static string MonitoringSettings {
            get {
                return ResourceManager.GetString("MonitoringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО «Форт-Телеком».
        /// </summary>
        public static string NameCompany {
            get {
                return ResourceManager.GetString("NameCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маска.
        /// </summary>
        public static string NetworkMask {
            get {
                return ResourceManager.GetString("NetworkMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат маски подсети.
        /// </summary>
        public static string NetworkMaskValidationError {
            get {
                return ResourceManager.GetString("NetworkMaskValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не авторизованы.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream NotificationSound {
            get {
                return ResourceManager.GetStream("NotificationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OFFLINE.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ONLINE.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На карте.
        /// </summary>
        public static string OnMap {
            get {
                return ResourceManager.GetString("OnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть веб интерфейс.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PoE.
        /// </summary>
        public static string Poe {
            get {
                return ResourceManager.GetString("Poe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подготовка к загрузке.
        /// </summary>
        public static string PreparingToUpload {
            get {
                return ResourceManager.GetString("PreparingToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon psw_disabled {
            get {
                object obj = ResourceManager.GetObject("psw_disabled", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon psw_enabled {
            get {
                object obj = ResourceManager.GetObject("psw_enabled", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузить устройство.
        /// </summary>
        public static string RebootDevice {
            get {
                return ResourceManager.GetString("RebootDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезапустить устройство?.
        /// </summary>
        public static string RebootDeviceConfirmation {
            get {
                return ResourceManager.GetString("RebootDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство перезапущено.
        /// </summary>
        public static string RebootSuccessful {
            get {
                return ResourceManager.GetString("RebootSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список адресов для отправки.
        /// </summary>
        public static string ReceiversList {
            get {
                return ResourceManager.GetString("ReceiversList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес получателя.
        /// </summary>
        public static string RecipientAddress {
            get {
                return ResourceManager.GetString("RecipientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить настройки.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сброшены.
        /// </summary>
        public static string ResetSuccessful {
            get {
                return ResourceManager.GetString("ResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск устройств.
        /// </summary>
        public static string SearchDevices {
            get {
                return ResourceManager.GetString("SearchDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки поиска.
        /// </summary>
        public static string SearchSettings {
            get {
                return ResourceManager.GetString("SearchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время поиска устройств в сети.
        /// </summary>
        public static string SearchTimeout {
            get {
                return ResourceManager.GetString("SearchTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на секунд.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать фон.
        /// </summary>
        public static string SelectBackground {
            get {
                return ResourceManager.GetString("SelectBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный файл.
        /// </summary>
        public static string SelectedFile {
            get {
                return ResourceManager.GetString("SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите модель.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлять уведомление при изменении доступности устройства.
        /// </summary>
        public static string SendEmailIfAvilabilityChanged {
            get {
                return ResourceManager.GetString("SendEmailIfAvilabilityChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес отправителя.
        /// </summary>
        public static string SenderAddress {
            get {
                return ResourceManager.GetString("SenderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для получения списка сенсоров отправьте IP-адрес устройства.
        /// </summary>
        public static string SendIpAddressToGetSensorList {
            get {
                return ResourceManager.GetString("SendIpAddressToGetSensorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить тестовое уведомление.
        /// </summary>
        public static string SendTestNotification {
            get {
                return ResourceManager.GetString("SendTestNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажата кнопка отправки тестового уведомления.
        /// </summary>
        public static string SendTestNotificationClicked {
            get {
                return ResourceManager.GetString("SendTestNotificationClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр.
        /// </summary>
        public static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения.
        /// </summary>
        public static string SensorErrorExceptionValue {
            get {
                return ResourceManager.GetString("SensorErrorExceptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус устройства.
        /// </summary>
        public static string SensorNameHostStatus {
            get {
                return ResourceManager.GetString("SensorNameHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период чтения сенсоров.
        /// </summary>
        public static string SensorReadPeriod {
            get {
                return ResourceManager.GetString("SensorReadPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серийный номер.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP-адрес сервера.
        /// </summary>
        public static string ServerIpAddress {
            get {
                return ResourceManager.GetString("ServerIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки применены.
        /// </summary>
        public static string SettingsConfirmed {
            get {
                return ResourceManager.GetString("SettingsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить настройки?.
        /// </summary>
        public static string SettingsSetConfirmation {
            get {
                return ResourceManager.GetString("SettingsSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки применены.
        /// </summary>
        public static string SettingsSetSuccessful {
            get {
                return ResourceManager.GetString("SettingsSetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо перезапустить приложение..
        /// </summary>
        public static string ShouldRestartAppMessage {
            get {
                return ResourceManager.GetString("ShouldRestartAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://tfortis.ru.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP-сервер.
        /// </summary>
        public static string SMTPServer {
            get {
                return ResourceManager.GetString("SMTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время ожидания ответа по SNMP.
        /// </summary>
        public static string SNMPAwait {
            get {
                return ResourceManager.GetString("SNMPAwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SNMP community.
        /// </summary>
        public static string SNMPCommunity {
            get {
                return ResourceManager.GetString("SNMPCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SNTP.
        /// </summary>
        public static string SNTP {
            get {
                return ResourceManager.GetString("SNTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировать.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSL шифрование.
        /// </summary>
        public static string SslProtection {
            get {
                return ResourceManager.GetString("SslProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать поиск.
        /// </summary>
        public static string StartSearching {
            get {
                return ResourceManager.GetString("StartSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на начать поиск устройств в сети.
        /// </summary>
        public static string StartTelegramSearching {
            get {
                return ResourceManager.GetString("StartTelegramSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        public static string StatusInfo {
            get {
                return ResourceManager.GetString("StatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string StatusOk {
            get {
                return ResourceManager.GetString("StatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem.
        /// </summary>
        public static string StatusProblem {
            get {
                return ResourceManager.GetString("StatusProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string StatusWarning {
            get {
                return ResourceManager.GetString("StatusWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Системная.
        /// </summary>
        public static string SystemTheme {
            get {
                return ResourceManager.GetString("SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8-800-100-112-8, (342) 260-20-30.
        /// </summary>
        public static string TelCompany {
            get {
                return ResourceManager.GetString("TelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки Telegram.
        /// </summary>
        public static string TelegramSettings {
            get {
                return ResourceManager.GetString("TelegramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Токен телеграм-бота.
        /// </summary>
        public static string TelegramToken {
            get {
                return ResourceManager.GetString("TelegramToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема приложения.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось времени.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Периодичность опроса.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часовой пояс.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление ПО, пожалуйста подождите.
        /// </summary>
        public static string UpdatingWait {
            get {
                return ResourceManager.GetString("UpdatingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на успешно загружен.
        /// </summary>
        public static string UploadedSuccessful {
            get {
                return ResourceManager.GetString("UploadedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время работы.
        /// </summary>
        public static string UpTime {
            get {
                return ResourceManager.GetString("UpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период проверки uptime.
        /// </summary>
        public static string UptimeCheckPeriod {
            get {
                return ResourceManager.GetString("UptimeCheckPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать аутентификацию.
        /// </summary>
        public static string UseAuthentificating {
            get {
                return ResourceManager.GetString("UseAuthentificating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оконный режим.
        /// </summary>
        public static string WindowedMode {
            get {
                return ResourceManager.GetString("WindowedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TFortis Device Manager | {0}.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш уникальный id:.
        /// </summary>
        public static string YourUniqueId {
            get {
                return ResourceManager.GetString("YourUniqueId", resourceCulture);
            }
        }
    }
}
